apiVersion: v1
kind: Service
metadata:
  name: firstdifferenceserver
  labels:
    app: firstdifferenceserver
    service: firstdifferenceserver
spec:
  ports:
  - port: 5001
    name: grpc-web # este debe ser el nombre para poder utilizar grpc web
    targetPort: 5001
  selector:
    app: firstdifferenceserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdifferenceserver
  labels:
    app: firstdifferenceserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstdifferenceserver
      version: v1
  template:
    metadata:
      labels:
        app: firstdifferenceserver
        version: v1
    spec:
      containers:
      - name: firstdifferenceserver
        image: ghcr.io/spoc-puj/first_difference:5001-11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      
