# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: abf_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'abf_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x62\x66_service.proto\x12\x06signal\"\"\n\nABFRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"*\n\x0b\x41\x42\x46Response\x12\x0f\n\x07numbers\x18\x01 \x03(\x02\x12\n\n\x02sp\x18\x02 \x01(\x05\x32\x42\n\nABFService\x12\x34\n\x07readAbf\x12\x12.signal.ABFRequest\x1a\x13.signal.ABFResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'abf_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ABFREQUEST']._serialized_start=29
  _globals['_ABFREQUEST']._serialized_end=63
  _globals['_ABFRESPONSE']._serialized_start=65
  _globals['_ABFRESPONSE']._serialized_end=107
  _globals['_ABFSERVICE']._serialized_start=109
  _globals['_ABFSERVICE']._serialized_end=175
# @@protoc_insertion_point(module_scope)
