apiVersion: v1
kind: Service
metadata:
  name: averageserver
  labels:
    app: averageserver
    service: averageserver
spec:
  ports:
  - port: 5001
    name: grpc-web # este debe ser el nombre para poder utilizar grpc web
    targetPort: 5001
  selector:
    app: averageserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: averageserver
  labels:
    app: averageserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: averageserver
      version: v1
  template:
    metadata:
      labels:
        app: averageserver
        version: v1
    spec:
      containers:
      - name: averageserver
        image: ghcr.io/spoc-puj/signals_average:5001-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      
