apiVersion: v1
kind: Service
metadata:
  name: fftconvolveserver
  labels:
    app: fftconvolveserver
    service: fftconvolveserver
spec:
  ports:
  - port: 5001
    name: grpc-web # este debe ser el nombre para poder utilizar grpc web
    targetPort: 5001
  selector:
    app: fftconvolveserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fftconvolveserver
  labels:
    app: fftconvolveserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fftconvolveserver
      version: v1
  template:
    metadata:
      labels:
        app: fftconvolveserver
        version: v1
    spec:
      containers:
      - name: fftconvolveserver
        image: ghcr.io/spoc-puj/fft_colvolve:5001-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
