# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mat_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mat_service.proto\x12\x06signal\"1\n\nMatRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\r\n\x05\x66ield\x18\x02 \x01(\t\"-\n\x0bMatResponse\x12\x1e\n\x06matrix\x18\x01 \x03(\x0b\x32\x0e.signal.Vector\"\x19\n\x06Vector\x12\x0f\n\x07numbers\x18\x01 \x03(\x02\x32\x42\n\nMatService\x12\x34\n\x07readMat\x12\x12.signal.MatRequest\x1a\x13.signal.MatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATREQUEST']._serialized_start=29
  _globals['_MATREQUEST']._serialized_end=78
  _globals['_MATRESPONSE']._serialized_start=80
  _globals['_MATRESPONSE']._serialized_end=125
  _globals['_VECTOR']._serialized_start=127
  _globals['_VECTOR']._serialized_end=152
  _globals['_MATSERVICE']._serialized_start=154
  _globals['_MATSERVICE']._serialized_end=220
# @@protoc_insertion_point(module_scope)
