apiVersion: v1
kind: Service
metadata:
  name: fftserver
  labels:
    app: fftserver
    service: fftserver
spec:
  ports:
  - port: 5001
    name: grpc-web # este debe ser el nombre para poder utilizar grpc web
    targetPort: 5001
  selector:
    app: fftserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fftserver
  labels:
    app: fftserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fftserver
      version: v1
  template:
    metadata:
      labels:
        app: fftserver
        version: v1
    spec:
      containers:
      - name: fftserver
        image: ghcr.io/spoc-puj/fft:5001-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
