apiVersion: v1
kind: Service
metadata:
  name: fastwavelettransformserver
  labels:
    app: fastwavelettransformserver
    service: fastwavelettransformserver
spec:
  ports:
  - port: 5001
    name: grpc-web # este debe ser el nombre para poder utilizar grpc web
    targetPort: 5001
  selector:
    app: fastwavelettransformserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastwavelettransformserver
  labels:
    app: fastwavelettransformserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastwavelettransformserver
      version: v1
  template:
    metadata:
      labels:
        app: fastwavelettransformserver
        version: v1
    spec:
      containers:
      - name: fastwavelettransformserver
        image: ghcr.io/spoc-puj/fast_wavelet_transform:5001-11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      
