apiVersion: v1
kind: Service
metadata:
  name: matreaderserver
  labels:
    app: matreaderserver
    service: matreaderserver
spec:
  ports:
  - port: 50052
    name: grpc-web # este debe ser el nombre para poder utilizar grpc web
    targetPort: 50052
  selector:
    app: matreaderserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matreaderserver
  labels:
    app: matreaderserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matreaderserver
      version: v1
  template:
    metadata:
      labels:
        app: matreaderserver
        version: v1
    spec:
      containers:
      - name: matreaderserver
        image: ghcr.io/spoc-puj/mat_reader:5001-5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
