apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: matreaderserver
spec:
  host: matreaderserver
  subsets:
  - name: v1
    labels:
      version: v1
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: matreadervs
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri: 
        prefix: /signal.MatService/readMat 
    route:
    - destination:
        host: matreaderserver
        port:
          number: 50052
        subset: v1
    corsPolicy:
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - grpc-timeout
        - content-type
        - keep-alive
        - user-agent
        - cache-control
        - content-type
        - content-transfer-encoding
        - custom-header-1
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
      maxAge: 1728s
      exposeHeaders:
        - custom-header-1
        - grpc-status
        - grpc-message
      allowCredentials: true