apiVersion: v1
kind: Service
metadata:
  name: movingaverageserver
  labels:
    app: movingaverageserver
    service: movingaverageserver
spec:
  ports:
  - port: 5001
    name: grpc-web # este debe ser el nombre para poder utilizar grpc web
    targetPort: 5001
  selector:
    app: movingaverageserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movingaverageserver
  labels:
    app: movingaverageserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movingaverageserver
      version: v1
  template:
    metadata:
      labels:
        app: movingaverageserver
        version: v1
    spec:
      containers:
      - name: movingaverageserver
        image: ghcr.io/spoc-puj/moving_average:5001-39
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      