apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spokmovingaverage
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ./Moving_Average/Deployment
    repoURL: https://github.com/SPOC-PUJ/microservices
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
