apiVersion: v1
kind: Service
metadata:
  name: runingsumserver
  labels:
    app: runingsumserver
    service: runingsumserver
spec:
  ports:
  - port: 5001
    name: grpc-web # Nombre para usar gRPC Web
    targetPort: 5001
  selector:
    app: runingsumserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runingsumserver
  labels:
    app: runingsumserver
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runingsumserver
      version: v1
  template:
    metadata:
      labels:
        app: runingsumserver
        version: v1
    spec:
      containers:
      - name: runingsumserver
        image: ghcr.io/spoc-puj/runing_sum:5001-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      
