name: Build and Push Docker Image for Fast Wavelet Transform

on:
  push:
    branches:
      - main
    paths:
      - 'FastWaveletTransform/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: 'SPOC-PUJ/microservices'
          token: ${{ secrets.GIT_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_MICROSERVICES }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./FastWaveletTransform
          push: true
          tags: |
            ghcr.io/spoc-puj/fast_wavelet_transform:${{ github.run_number }}
            ghcr.io/spoc-puj/fast_wavelet_transform:5001-${{ github.run_number }}
      - name: Modify the deployment manifest
        working-directory: ./FastWaveletTransform/Deployment
        run: |
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git config user.name "${{ secrets.GIT_NAME }}"
          pwd
          ls
          sed -i "s+ghcr.io/spoc-puj/fast_wavelet_transform:.*+ghcr.io/spoc-puj/fast_wavelet_transform:5001-${{ github.run_number }}+g" FastWaveletTransformBack.yaml
          git add .
          git commit -m "Update Deployment with image version ${{ github.run_number }}"
          git push origin main --force
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}
  build-and-push-arm64:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_MICROSERVICES }}

      - name: Build and push ARM64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./FastWaveletTransform
          dockerfile: ./Dockerfile_arm
          push: true
          tags: |
            ghcr.io/spoc-puj/fast_wavelet_transform:arm64-latest
            

