name: Build and Push Docker Image for FirstDifference

on:
  push:
    paths:
      - 'FirstDifference/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_MICROSERVICES }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./FirstDifference
          push: true
          tags: |
            ghcr.io/spoc-puj/FirstDifference:latest
            ghcr.io/spoc-puj/FirstDifference:5000-latest
